<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Automator</name>
   <tag></tag>
   <elementGuidId>66cdf559-f4b1-4353-b42a-1a5439bc143f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tags-input[@id='3547']/div/auto-complete/div/ul/li/ti-autocomplete-match/ng-include/span/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automator</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3547&quot;)/div[@class=&quot;host&quot;]/auto-complete[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;autocomplete ng-scope&quot;]/ul[@class=&quot;suggestion-list&quot;]/li[@class=&quot;suggestion-item ng-scope selected&quot;]/ti-autocomplete-match[@class=&quot;ng-isolate-scope&quot;]/ng-include[@class=&quot;ng-scope&quot;]/span[@class=&quot;ng-binding ng-scope&quot;]/em[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//tags-input[@id='3547']/div/auto-complete/div/ul/li/ti-autocomplete-match/ng-include/span/em</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automator'])[1]/following::em[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[2]/preceding::em[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a tag'])[1]/preceding::em[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//span/em</value>
   </webElementXpaths>
</WebElementEntity>
